<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\FocusTray.Core\FocusTray.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Kubis1982.Atlassian.Jira.RestClient.v3" Version="1.8453.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
